### PR TITLE
添加canvas层鼠标穿透效果

### PR DESCRIPTION
**Pull request by lancelot-lewis**
现在默认的canvas动画效果只在文章主体外部显示，所以在手机端无法看到canvas动画，将`z-index`值去掉之后，同时添加`pointer-events: none;`属性，可以实现将canvas动画显示在文章内容上，并且不影响页面点击事件

### CODE REVIEW

**Comment by ivan-nginx** [comment]
請用英文寫。

**Comment by sli1989** [comment]
~~Con't reproduce u statement. The canvas displays in full page as well as the content.~~

oh, I got u point. but it's a choice for users to whether display or not in content.

**Comment by stevenjoezhang** [comment]
但是这样看上去很奇怪...

**Comment by stevenjoezhang** [comment]
安装方式已更新，请查看最新的 README ： https://github.com/theme-next/theme-next-canvas-nest/blob/master/README.md

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/theme-next/theme-next-canvas-nest">theme-next/theme-next-canvas-nest</a></strong></div><div>canvas-nest.js for NexT. Contribute to theme-next/theme-next-canvas-nest development by creating an account on GitHub.</div></blockquote>

**Pull request closed without merging**
